# Generated by Django 4.1.5 on 2023-01-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_post_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TN', 'Танки'), ('HL', 'Хилы'), ('DD', 'ДД'), ('SL', 'Торговцы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('HS', 'Кузнецы'), ('SK', 'Кожевники'), ('PO', 'Зельевары'), ('SM', 'Мастера заклинаний')], default='TN', max_length=2, verbose_name='Название Категории'),
        ),
    ]
